const declarationKinds = [
  'DeclarationKindValue',
  'DeclarationKindFunction',
  'DeclarationKindVariable',
  'DeclarationKindConstant',
  'DeclarationKindType',
  'DeclarationKindParameter',
  'DeclarationKindArgumentLabel',
  'DeclarationKindStructure',
  'DeclarationKindResource',
  'DeclarationKindContract',
  'DeclarationKindEvent',
  'DeclarationKindField',
  'DeclarationKindInitializer',
  'DeclarationKindDestructorLegacy',
  'DeclarationKindStructureInterface',
  'DeclarationKindResourceInterface',
  'DeclarationKindContractInterface',
  'DeclarationKindEntitlement',
  'DeclarationKindEntitlementMapping',
  'DeclarationKindImport',
  'DeclarationKindSelf',
  'DeclarationKindBase',
  'DeclarationKindTransaction',
  'DeclarationKindPrepare',
  'DeclarationKindExecute',
  'DeclarationKindTypeParameter',
  'DeclarationKindPragma',
  'DeclarationKindEnum',
  'DeclarationKindEnumCase',
  'DeclarationKindAttachment',
];
const typeDeclarationKinds = [
  'DeclarationKindStructure',
  'DeclarationKindResource',
  'DeclarationKindContract',
  'DeclarationKindEntitlement',
  'DeclarationKindEntitlementMapping',
  'DeclarationKindEvent',
  'DeclarationKindStructureInterface',
  'DeclarationKindResourceInterface',
  'DeclarationKindContractInterface',
  'DeclarationKindTypeParameter',
  'DeclarationKindEnum',
  'DeclarationKindAttachment',
];
const interfaceDeclarationKinds = [
  'DeclarationKindContractInterface',
  'DeclarationKindStructureInterface',
  'DeclarationKindResourceInterfac',
];

module.exports = {
  declarationKinds,
  typeDeclarationKinds,
  interfaceDeclarationKinds,
};
